[package]
name = "complex_math"
version = "0.1.0"
edition = "2021"

[lib]
name = "complex_math"
crate-type = ["cdylib"]

[dependencies]
num-complex = "0.4"

[profile.release]
opt-level = 3
lto = true
